networks:
  nightingale:
    driver: bridge

services:
  tendis:
    image: "swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/tencentdbforkv/tendisplus:v2.8.0"
    container_name: tendis
    hostname: tendis
    restart: always
    environment:
      TZ: Asia/Shanghai
      CLUSTER: "no"
      REDIS_PASSWORD: "test123*6"
    networks:
      - nightingale
    ports:
      - "51002:51002"


#  victoriametrics:
#    image: victoriametrics/victoria-metrics:v1.79.12
#    container_name: victoriametrics
#    hostname: victoriametrics
#    restart: always
#    environment:
#      TZ: Asia/Shanghai
#    ports:
#      - "8428:8428"
#    networks:
#      - nightingale
#    command:
#      - "--loggerTimezone=Asia/Shanghai"
  opengeminidb:
    image: opengeminidb/opengemini-server:latest
    container_name: opengeminidb
    hostname: opengeminidb
    restart: always
    environment:
      TZ: Asia/Shanghai
    networks:
      - nightingale

  nightingale:
    image: swr.cn-north-4.myhuaweicloud.com/zj-base/nightingale:latest
    container_name: nightingale
    hostname: nightingale
    restart: always
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: tendis:51002
    volumes:
      - ./etc-nightingale:/app/etc
    networks:
      - nightingale
    ports:
      - "17000:17000"
      - "20090:20090"
    depends_on:
      - tendis
      - opengeminidb
    command:
      - /app/n9e

  categraf:
    image: "swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/flashcatcloud/categraf:v0.5.6"
    container_name: "categraf"
    hostname: "categraf01"
    restart: always
    environment:
      TZ: Asia/Shanghai
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_MOUNT_PREFIX: /hostfs
      WAIT_HOSTS: nightingale:17000, nightingale:20090
    volumes:
      - ./etc-categraf:/etc/categraf/conf
      - /:/hostfs
    networks:
      - nightingale
    depends_on:
      - nightingale
